server:
  session:
    timeout: 1800
  port: 9093

#spring相关
spring:
  application:
    name: user-manage-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/admin_user?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      poolName: InstitutionHikariCP
      maximumPoolSize: 5
      minimumIdle: 3
      maxLifetime: 2000000
      connectionTimeout: 30000
      idleTimeout: 30000
      dataSourceProperties:
        # opt for mysql
        cachePrepStmts: true
        useServerPrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379

mybatis:
  type-aliases-package: com.guns21.**.entity
  mapper-locations: classpath*:mapper/*.xml
com:
  guns21:
    security:
      anonymous:
        disable: false
      login: /api/v1/user/login
      logout: /api/v1/user/logout
      permit-pages: /api/v1/sms/sendCode
      message:
        password-error: 验证码错误
      auth-url: /api/v1/user/userInfo
